### PR TITLE
fix: Check if _s exists in ConnectionManager before deleting it

### LINKED ISSUE #423: `KeycloakOpenIDConnection` object has no attribute '_s'
After updating to 2.13.2, I keep encountering this error. I do not call it directly, nor I am aware of me using it within any context manager
```
  Traceback (most recent call last):
    File "keycloak/connection.py", line 89, in __del__
      self._s.close()
  AttributeError: 'KeycloakOpenIDConnection' object has no attribute '_s'
```

### PR DESCRIPTION
**Pull request by pehala**
Simple but ugly fix. A better option would be to move the `__init__` call in `KeycloakOpenIDConnection`, which is impossible due to custom_headers.

Fixes #423

### CODE REVIEW

**Comment by ryshoooo** [comment]
LGTM. However, to be frank, I'm not sure why the `__del__` is overridden in the first place. Also based on mcoding's analysis (https://www.youtube.com/watch?v=IFjuQmlwXgU), `__del__`'s behavior is just really confusing and leads to unnecessary errors. I'd be fine if the entire `def __del__...` is removed :)

**Comment by pehala** [comment]
I think it is because of session management. I believe not closing them could potentially leave the socket open on OS, until termination. But yeah `__del__` is a TERRIBLE way how to manage it

**Comment by ryshoooo** [comment]
> I think it is because of session management. I believe not closing them could potentially leave the socket open on OS, until termination.

Right, I see. The request's Session does not close it upon destruction unless it's used as a context manager :) alright then
