### ISSUE TITLE
`KeycloakOpenIDConnection` object has no attribute '_s'

### ISSUE THREAD

**Issue by pehala** [marcospereirampj/python-keycloak#423]
After updating to 2.13.2, I keep encountering this error. I do not call it directly, nor I am aware of me using it within any context manager
```
  Traceback (most recent call last):
    File "keycloak/connection.py", line 89, in __del__
      self._s.close()
  AttributeError: 'KeycloakOpenIDConnection' object has no attribute '_s'
```

**Comment by magicwind** [comment]
same issue when run: 
keycloak_admin = KeycloakAdmin(...)

pkg:
python-keycloak    2.13.2

**Comment by pehala** [comment]
I have found out the root cause and reproducer. 

Create `KeycloakAdmin` pointing to an invalid URL, it will fail (specifically `get_token()` method will fail in `KeycloakOpenIDConnection.__init__`) with exception and it never gets to  `ConnectionManager.__init__`. However,  `del` will still be called (once it will get garbage collected).
